# 请按照格式规范修改 (写插件的第5天)
# 插件版本 ${project.version}
# 交流群:
# BUG反馈qq:1758041568
#版本号
version: ${project.version}
#是否开启更新检测
checkNewVersion: true
#语言文本
lang: zh_CN.yml
#装备词条上面的名字
table: '§f-----------------§8§l飞升属性栏§f-----------------'
# 0表示正常顺序1表示lore显示在第一列
order: true
#包含哪些字符可以强化不要和起它物品重名，不然可能导致多判,抽时间修复
include: ''
# 切记不要删除 :
attribute:
  #头部
  head:
    - '§3物理防御:'
    - '§3暴击抗性:'
  #胸部
  cuirass:
    - '§3物理防御:'
    - '§3暴击抗性:'
  #腿部
  pants:
    - '§3物理防御:'
    - '§3暴击抗性:'
  #脚部
  shoe:
    - '§3物理防御:'
    - '§3暴击抗性:'
  #手部(包括副手)
  hand:
    - '§3物理伤害:'
    - '§3暴击几率:'
#成功几率
succeed:
  1: 60
  2: 60
  3: 60
  4: 60
  5: 60
  6: 60
  7: 60
  8: 60
  9: 60
  10: 60
  11: 60
  12: 60
  13: 60
  14: 60
  15: 60
  16: 60
#属性强化范围 每级增加的属性范围
attributeRange:
  1: '5-10'
  2: '20-50'
  3: '100-300'
  4: '400-500'
  5: '500-600'
  6: '600-700'
  7: '700-800'
  8: '800-900'
  9: '900-1000'
  10: '1000-1100'
  11: '1100-1200'
  12: '1200-1300'
  13: '1300-1400'
  14: '1400-1500'
  15: '1500-1600'
  16: '1600-1700'
